name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          bun install --ignore-scripts
        shell: bash
      - name: Run tests
        run: |
          bun run test
        shell: bash

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          bun install --ignore-scripts
        shell: bash
      - name: Build application
        run: |
          bun run build
        shell: bash
